# Generated by Django 4.2.2 on 2023-08-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_cart_category_remove_book_description_and_more'),
    ]

    operations = [
    ]
