# Generated by Django 4.2.2 on 2023-08-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
